#!/bin/bash

# This fantastic piece of engineering is because I can't figure out how to do the equivalent in Browserify
# without ending up with a 500k pile of goop that doesn't function.   Pull requests welcome.

mkdir -p browser 

cat scripts/preamble.js                                                > browser/nitrogen.js
cat manager/cameraManager.js | sed '/require(/d' | sed '/module.export/d' >> browser/nitrogen.js

cat scripts/module.js                                                  >> browser/nitrogen.js
cat scripts/postamble.js                                               >> browser/nitrogen.js

# these will be mixed in with their main client library equilvalents.
uglifyjs browser/nitrogen.js -o browser/nitrogen-min.js

# build documentation

yuidoc .
sed -i '' -e 's/\.\//\/docs\//g' docs/index.html
