#!/bin/bash

mkdir -p browser 

cat scripts/preamble.js                                                > browser/nitrogen-switch.js
cat manager/switchManager.js | sed '/require(/d' | sed '/module.export/d' >> browser/nitrogen-switch.js

cat scripts/module.js                                                  >> browser/nitrogen-switch.js
cat scripts/postamble.js                                               >> browser/nitrogen-switch.js

# these will be mixed in with their main client library equilvalents.
node_modules/.bin/uglifyjs browser/nitrogen-switch.js > browser/nitrogen-switch-min.js

# build documentation

node_modules/.bin/yuidoc .
