#!/bin/bash

mkdir -p browser 

cat scripts/preamble.js                                                > browser/nitrogen.js
cat manager/switchManager.js | sed '/require(/d' | sed '/module.export/d' >> browser/nitrogen.js

cat scripts/module.js                                                  >> browser/nitrogen.js
cat scripts/postamble.js                                               >> browser/nitrogen.js

# these will be mixed in with their main client library equilvalents.
uglifyjs browser/nitrogen-switch.js -o browser/nitrogen-switch-min.js

# build documentation

yuidoc .
sed -i '' -e 's/\.\//\/docs\//g' docs/index.html
